README.md, package.json, src/comms/ECLWorkunit.ts, src/comms/WsWorkunits.ts, src/debugger/ECLDebugSession.ts
Adding support for https connections and ability to ignore unauthorized requests e.g. ssl certificate issues for self signed certificates
=> Adding support for https connections

package.json, src/debugger/ECLDebugSession.ts, src/eclCheck.ts, src/files/clientTools.ts, tsconfig.json
=> GH-14 Add eclccPath to settings + launch configuration

.gitmodules, package.json, src/debugger/ECLDebugSession.ts, src/eclCheck.ts, src/eclCodeAction.ts, src/eclDeclaration.ts, src/eclMode.ts, src/eclStatus.ts, src/eclSuggest.ts, src/files/clientTools.ts, src/util.ts, yarn.lock
Fix lint issues
Fix debugging exception
=> Switch to new comms package.json

src/debugger/ECLDebugSession.ts, src/eclCheck.ts, src/eclMain.ts, src/eclStatus.ts, tslint.json
=> GH-24-EchoClientToolsVersion

package.json
=> Up third party libraries to latest.

package.json, src/eclMain.ts
=> GH-3 Update ECL language reference links

package.json
=> GH-5 Autocomplete Std

package-lock.json
=> GH-36 Switch from yarn to package-lock

src/debugger/ECLDebugSession.ts, src/eclCheck.ts, src/eclDeclaration.ts, src/eclMain.ts, src/eclSuggest.ts, src/eclWatch.ts, src/util.ts, tsconfig.json
=> GH-43 Use latest TS strict settings

src/eclCheck.ts, src/eclMain.ts, src/eclSuggest.ts
Issue when includeFolders is a relative path
Issue when included folder does not exist
Fixes GH-33
=> GH-33 ecl.includeFolders issue

src/eclMain.ts
=> GH-37 On open, syntax check visible windows.

src/debugger/ECLDebugSession.ts, src/eclCheck.ts, src/eclMain.ts, src/util.ts
(PR is dependent on https://github.com/GordonSmith/vscode-ecl/pull/46)
=> GH-40 Logging not working as expected 

src/eclCheck.ts
(Dependent on PR: https://github.com/GordonSmith/vscode-ecl/pull/46)
=>  GH-41 Syntax check should not clear all previous errors

package.json, src/eclCheck.ts, src/eclMain.ts
Dependent on PR:  https://github.com/GordonSmith/vscode-ecl/pull/48
=> GH-4 Syntax check all files

package.json, src/debugger/ECLDebugSession.ts, src/eclCheck.ts, src/eclCommand.ts, src/eclDiagnostic.ts, src/eclEditor.ts, src/eclMain.ts, src/eclStatus.ts, src/eclTree.ts, src/eclWatch.ts
=> GH-52 Add initial WU Support

README.md, package.json, src/eclCommand.ts, src/eclDiagnostic.ts
=> GH-61 On close file, remove its err/warn from the problems list.

README.md, package.json, src/eclCommand.ts, src/eclTree.ts, src/util.ts
Auto open created WUs.
Fixes GH-59
=> GH-59 Optionally open WUs in external browser

.gitignore, README.md, package.json, src/eclCheck.ts
Allow user to override syntax check args
Fixes GH-66
=> GH-66 Override Syntax Args

README.md, package.json, src/eclMain.ts
Allow user to enable debug logging
Fixes GH-67
=> GH-67 Optional Debug Logging

README.md, package-lock.json, package.json, src/eclTree.ts, tsconfig.json
=> GH-75 Update references to upstream repo

src/eclCheck.ts, src/eclEditor.ts
=> GH-79 Syntax check fails when syntaxCheckOnSave=true

README.md, package.json
=> GH-76 Default WUOpenExternal to true.

package-lock.json, package.json, src/eclCommand.ts
Remove opn dependency
Fixes GH-83
=> GH-83 Remove moment dependency

package-lock.json, package.json, src/debugger/ECLDebugSession.ts, tsconfig.json
Move ECL Definition specific code into vscode.
=> GH-90 Update to latest packages

images/ecl-explorer.svg, package.json
=> GH-91 Move ECL Watch links into its own activity.

test/ecl.test.ts, test/index.ts, tslint.json
=> chore: Fix lint config and issues

package.json
=> fix: Add support for ecllib files

src/debugger/ECLDebugSession.ts, src/debugger/launchConfig.ts, src/eclCheck.ts
=> fix:  Autopick best eclcc version

package.json
=> chore: Update to latest @hpcc-js/comms

README.md, package.json, src/debugger/ECLDebugSession.ts, src/debugger/launchConfig.ts, src/eclConfigProvider.ts, src/eclMain.ts
=> fix: Prompt user for missing password

src/eclDiagnostic.ts
=> fix(Syntax Check): Illegal argument: line must be non-negative

src/eclCheck.ts
=> fix(Syntax Check): Check for valid line + col

package.json
Includes fixed ECL Error parser.
=> fix(Syntax Check): Use latest @hpcc-js/comms

package-lock.json, package.json, src/debugger/launchConfig.ts, src/eclConfigProvider.ts
=> fix(credentials): Credential prompt fails

package-lock.json, package.json
=> chore(build): Remove unused dependency

package-lock.json, package.json
=> chore(publish): Tweak publish scripts

.vscodeignore, package-lock.json, package.json
Make VSCode required version to be "soft"
=> fix:  Missing comms dependency

package.json
=> chore(travis): Minimal test for travis

package-lock.json, package.json, src/ecl/command.ts
=> chore(vscode): Update API to open external web page

src/debugger/ECLDebugSession.ts
=> feat: Support XML archive submissions

package.json, src/debugger/launchConfig.ts, src/ecl/configProvider.ts
=> fix(comms): "rejectUnauthorized" was not being honoured

package-lock.json, package.json, src/ecl/documentSymbolProvider.ts, src/ecl/main.ts
=> feat(Overview): Add document symbol support from meta information

package.json
=> fix(publish): Add (R) to company name

package-lock.json, package.json, src/ecl/declaration.ts, src/ecl/suggest.ts
Bump @hpcc-js versions
Fixed deprecated VSCode API items
=> fix(problems): Error parse failed when path contained a space.

src/ecl/declaration.ts, src/ecl/suggest.ts
=> fix(F12) Rollback use of deprecated "rootPath"

.gitignore, .vscode/launch.json, .vscode/settings.json, .vscodeignore, package-lock.json, package.json, rollup.config.js, src/dashy/View.ts, src/dashy/diff.ts, src/debugger.ts, src/debugger/ECLDebugSession.ts, tsconfig.json
=> feat(build): Bundle extension

package.json, src/ecl/check.ts, src/ecl/clientTools.ts, src/ecl/command.ts, src/ecl/status.ts
=> feat(ClientTools): Add quick select specific eclcc version 

README.md, package.json, src/ecl/command.ts
=> chore(readme): Updated readme file.

src/ecl/main.ts, src/ecl/terminal.ts
Picks version based on same logic as submit
=> feat(terminal): Add command to open ECL terminal.ts

snippets/ecl.json
Added Added most of the commonly used:
* STD library
* Data types
* Function and macro templates
* Reserved function grouping including dedup and join.
=> feat(snippets):  Enhanced Snippets

README.md
=> fix(README.md): Add information for KEL

src/kel/clientTools.ts, src/kel/command.ts
=> chore(logging): Additional logging

src/kel/clientTools.ts, src/kel/parser.ts
=> fix(KEL): Check syntax was throwing away the errors.

package-lock.json, package.json, src/debugger/ECLDebugSession.ts, src/debugger/launchConfig.ts, src/ecl/configProvider.ts
Add extra logging for non debug case.
=> fix(DebugSession): Enable debug logging

src/debugger/ECLDebugSession.ts
=> fix(DebugSession): Workaround VSCode regression

syntaxes/kel.tmLanguage.json
=> fix(KEL): Improve syntax lexing

README.md, package.json, src/ecl/command.ts, src/hpccplatform/launchConfig.ts, src/hpccplatform/session.ts
Add command to lookup and insert a logical files record definition.
=> feat:  Insert Record Definition

package-lock.json, package.json, src/hpccplatform/launchConfig.ts, src/hpccplatform/session.ts
Also improved failed WU Submit reporting
=> fix:  Performance issue

src/hpccplatform/launchConfig.ts
legacyFlag not getting set correctly.
=> fix: User/PW not prompting on demand

src/ecl/check.ts, src/hpccplatform/launchConfig.ts, src/hpccplatform/session.ts
=> fix(workspace): Auto includes not getting calculated for submit

src/ecl/command.ts
=> feat(Insert Record): Offer list of logical files when possible

package.json, src/ecl/command.ts, src/ecl/eclWatchTree.ts
=> feat(WU Tree):  Add context menu to WU Items

src/ecl/eclWatchPanelView.ts, src/eclwatch/WUDetails.tsx
Fixed race condition with saved state
=> fix(Results):  Edge case with 0 issues and 0 rows

.github/workflows/publish-marketplace.yml, .github/workflows/pull-build-test.yml, README.md, package.json, src/dashy/diff.ts
=> chore: Switch from "master" to "trunk"

src/ecl/command.ts
=> fix(sign):  Allow blank passphrases

syntaxes/kel.tmLanguage.json
=> feat(kel): enhance KEL lexer for better visualization

README.md, package-lock.json, package.json, package.nls.json, src/ecl/command.ts, src/hpccplatform/launchConfig.ts, src/hpccplatform/session.ts
=> feat(codesign): Added verify ECL signature command

package.json, snippets/kel.json
=> feat(kel): adding KEL snippets to vscode-ecl

src/eclwatch.tsx, src/eclwatch/WUResult.tsx
=> fix:  Add support for SET OF to Copy As ECL

syntaxes/ecl.tmLanguage.json
=> fix(lexer) Fix ecl lexer

src/ecl/command.ts
=> fix: Import mod file parses extension incorrectly

README.md, ecl-sample/.vscode/launch.json, package.json
=> fix:  Remove "play.hpccsystems.com" from launch snippets

syntaxes/ecl.tmLanguage.json
=> fix: lexer for ecl

.github/workflows/publish-github.yml
=> chore(publish):  Add assets to release in GitHub

.github/workflows/publish-github.yml
=> chore(publish):  Rename github action

syntaxes/ecl.tmLanguage.json
=> LEXER-007 Fixed keyword and function problems

src/util/localize.ts
=> fix(language):  Language pack resolver causing issue with GitPod

README.md, package.json, package.nls.json, src/hpccplatform/launchConfig.ts
=> feat:  Added ecl.forceProxySupport setting

.github/workflows/publish-github.yml, ecl-sample/.vscode/launch.json, package.json
=> chore: Remove version from GitHub asset vsix 

package-lock.json, package.json
=> chore(security): Bump package versions

src/ecl/eclWatchPanelView.ts, src/eclwatch.tsx, src/eclwatch/messages.ts
=> fix:  Only use AbortController when needed

src/hpccplatform/launchConfig.ts
=> fix:  Include user launch configurations in list

src/hpccplatform/launchConfig.ts
=> fix: eclccLogFile repeats on each process call

.vscode/settings.json, package.json, syntaxes/dashy.tmLanguage.json, syntaxes/kel.tmLanguage.json
=> fix: Dashy files do not auto-activate the plugin

src/ecl/eclWatchPanelView.ts, src/ecl/eclWatchTree.ts, src/hpccplatform/session.ts
=> fix(notebook):  Suppress WU panel on notebook submit

package.json
=> fix(notebook):  Add ObservableJS dependency

src/ecl/command.ts
=> feat: Auto focus problems on syntax check

src/ecl/command.ts
Manually index the searchable terms
=> fix: Update shift+F1 help URLs

src/ecl/editor.ts, src/kel/editor.ts
=> GH-339 Honour Syntax-check on load

.vscode/launch.json, README.md, package.json, package.nls.json, src/hpccplatform/launchConfig.ts, src/hpccplatform/session.ts
=> feat:  Added pingInterval setting

src/notebook/controller/controller.ts, src/notebook/controller/serializer.ts
=> fix: Cell tracking issue, with unsaved notebooks

README.md, package.json, package.nls.json, src/ecl/eclWatchPanelView.ts, src/ecl/eclWatchTree.ts
Available options:
* internal
* external
* disabled
=> feat:  Add  WUShowResults setting

package.json
=> feat: Add right-click menus to Bundles and Client Tools

package.json, package.nls.json
=> fix: add translate string to Set State in WU context menu

src/ecl/eclWatchTree.ts
=> fix: change start year from 1970 to 2000 in WU listing

package.json
=> fix: Right click WU->Result has wrong menu item

src/ecl/eclWatchTree.ts
=> fix: Localize previous week strings

.vscode/launch.json, package-lock.json, package.json, util/generate.ts, util/googtrans.py, util/index.ts, util/merge.ts, util/nls/util.ts, util/nls/vscode.ts
Update nls scripts to include previous week phrases, use google translate, and merge new translations.
#409
=> fix: update nls scripts

util/nls/vscode.ts
=> fix: add submenus, views, notebooks, and notebookRenderer to fixPackage

util/nls/vscode.ts
=> feat: remove orphan localization strings
